[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}\
### {{ group }}
{% for commit in commits %}\
- {{ commit.message | upper_first }} ([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/seanseannery/opsfile/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}\
"""
trim = true

[git]
conventional_commits  = true
filter_unconventional = true
tag_pattern           = "v[0-9].*"

commit_parsers = [
  { message = "^feat",     group = "Features (feat:*)"       },
  { message = "^fix",      group = "Bug Fixes (fix:*)"       },
  { message = "^docs",     group = "Documentation (docs:*)"   },
  { message = ".*",        group = "Other (*)"           },
]
